# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CXX=/usr/bin/gcc
MXX=/usr/bin/gcc
AS=/usr/bin/gcc
MM=/usr/bin/gcc
CU=/usr/bin/clang
CC=/usr/bin/gcc

AR=/usr/bin/ar
SH=/usr/bin/g++
LD=/usr/bin/g++

readpe_AR=/usr/bin/ar
readpe_CC=/usr/bin/gcc
readpe_test_LD=/usr/bin/g++
readpe_test_CC=/usr/bin/gcc

readpe_CCFLAGS=-m64 -g -Wall -Wextra -O0 -I. -DDEBUG
readpe_ARFLAGS=-cr
readpe_test_CCFLAGS=-m64 -g -Wall -Wextra -O0 -I. -DDEBUG
readpe_test_LDFLAGS=-m64 -Lbuild/linux/x86_64/debug -lreadpe

default:  readpe readpe_test

all:  readpe readpe_test

.PHONY: default all  readpe readpe_test

readpe: build/linux/x86_64/debug/libreadpe.a
build/linux/x86_64/debug/libreadpe.a: build/.objs/readpe/linux/x86_64/debug/src/readpe.c.o build/.objs/readpe/linux/x86_64/debug/src/read_element.c.o build/.objs/readpe/linux/x86_64/debug/src/utils.c.o
	@echo linking.debug libreadpe.a
	@mkdir -p build/linux/x86_64/debug
	$(VV)$(readpe_AR) $(readpe_ARFLAGS) build/linux/x86_64/debug/libreadpe.a build/.objs/readpe/linux/x86_64/debug/src/readpe.c.o build/.objs/readpe/linux/x86_64/debug/src/read_element.c.o build/.objs/readpe/linux/x86_64/debug/src/utils.c.o

build/.objs/readpe/linux/x86_64/debug/src/readpe.c.o: src/readpe.c
	@echo compiling.debug src/readpe.c
	@mkdir -p build/.objs/readpe/linux/x86_64/debug/src
	$(VV)$(readpe_CC) -c $(readpe_CCFLAGS) -o build/.objs/readpe/linux/x86_64/debug/src/readpe.c.o src/readpe.c

build/.objs/readpe/linux/x86_64/debug/src/read_element.c.o: src/read_element.c
	@echo compiling.debug src/read_element.c
	@mkdir -p build/.objs/readpe/linux/x86_64/debug/src
	$(VV)$(readpe_CC) -c $(readpe_CCFLAGS) -o build/.objs/readpe/linux/x86_64/debug/src/read_element.c.o src/read_element.c

build/.objs/readpe/linux/x86_64/debug/src/utils.c.o: src/utils.c
	@echo compiling.debug src/utils.c
	@mkdir -p build/.objs/readpe/linux/x86_64/debug/src
	$(VV)$(readpe_CC) -c $(readpe_CCFLAGS) -o build/.objs/readpe/linux/x86_64/debug/src/utils.c.o src/utils.c

readpe_test: build/linux/x86_64/debug/readpe_test
build/linux/x86_64/debug/readpe_test: build/linux/x86_64/debug/libreadpe.a build/.objs/readpe_test/linux/x86_64/debug/main.c.o
	@echo linking.debug readpe_test
	@mkdir -p build/linux/x86_64/debug
	$(VV)$(readpe_test_LD) -o build/linux/x86_64/debug/readpe_test build/.objs/readpe_test/linux/x86_64/debug/main.c.o $(readpe_test_LDFLAGS)

build/.objs/readpe_test/linux/x86_64/debug/main.c.o: main.c
	@echo compiling.debug main.c
	@mkdir -p build/.objs/readpe_test/linux/x86_64/debug
	$(VV)$(readpe_test_CC) -c $(readpe_test_CCFLAGS) -o build/.objs/readpe_test/linux/x86_64/debug/main.c.o main.c

clean:  clean_readpe clean_readpe_test

clean_readpe: 
	@rm -rf build/linux/x86_64/debug/libreadpe.a
	@rm -rf build/linux/x86_64/debug/readpe.sym
	@rm -rf build/.objs/readpe/linux/x86_64/debug/src/readpe.c.o
	@rm -rf build/.objs/readpe/linux/x86_64/debug/src/read_element.c.o
	@rm -rf build/.objs/readpe/linux/x86_64/debug/src/utils.c.o

clean_readpe_test:  clean_readpe
	@rm -rf build/linux/x86_64/debug/readpe_test
	@rm -rf build/linux/x86_64/debug/readpe_test.sym
	@rm -rf build/.objs/readpe_test/linux/x86_64/debug/main.c.o

